language: node_js

node_js:
  - "4.4.7"
  - "6.3.0"

sudo: false

branches:
  only:
    - master

before_install:
  - 'npm install -g npm@3'

script:
  - npm --version
  - npm run coverage
  - nyc report --reporter=text-lcov | node_modules/.bin/coveralls || echo "Coveralls upload failed"

  - npm prune --production
  - npm run build


